name: Deploy to Azure
on: 
  push:
    branches:
      - main
env:
  APP_WEBAPP_NAME: carecirle-gol
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: Install dependencies
        run: pnpm install
        
      - name: Lint
        run: pnpm lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: List Build
        run: ls -la
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: .next
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Echo build
        run: ls -la
      - name: Echo secrets.AZURE_PUBLISH_PROFILE
        run: echo ${{ secrets.AZURE_PUBLISH_PROFILE }}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .